---
title: "HW_05"
author: "MINSI SUNG"
date: "14/10/2019"
output:
    html_document:
    keep_md: yes
    number_sections: yes
    toc: yes
    toc_float: yes
---

```{r , warning=FALSE,echo=FALSE}
suppressPackageStartupMessages(library(tidyverse)) 
suppressPackageStartupMessages(library(gapminder))
suppressPackageStartupMessages(library(knitr))
```


# Exercise 1:Explain the value of the here::here package

### Read through the [blog post by Malcolm Barrett](https://malco.io/2018/11/05/why-should-i-use-the-here-package-when-i-m-already-using-projects/) where he outlines why one should use the here::here package in RStudio projects.

### Task: In your own words, summarize the value of the here::here package in 250 words or fewer.



# Exercise 2: Factor management

### Task: Choose **one** dataset (of your choice) and a variable to explore. After ensuring the variable(s) you’re exploring are indeed factors, you should:


### 1. Drop factor / levels;
### 2. Reorder levels based on knowledge from data.

### We’ve elaborated on these steps for the gapminder and singer data sets below. Explore the effects of re-leveling a factor in a tibble by:

### 1. comparing the results of <span style="color:red">arrange</span> on the original and re-leveled factor.
### 2. Plotting a figure of before/after re-leveling the factor (make sure to assign the factor to an aesthetic of your choosing).
### These explorations should involve the data, the factor levels, and at least two figures (before and after.

## **Elaboration for the gapminder data set**
### **Drop Oceania.** Filter the Gapminder data to remove observations associated with the <span style="color:red">continent</span> of Oceania. Additionally, remove unused factor levels. Provide concrete information on the data before and after removing these rows and Oceania; address the number of rows and the levels of the affected factors.

### **Reorder the levels of <span style="color:red">country</span> or <span style="color:red">continent</span>.** Use the forcats package to change the order of the factor levels, based on summarized information of one of the quantitative variables. Consider experimenting with a summary statistic beyond the most basic choice of the mean/median. Use the <span style="color:red">forcats</span> package in the tidyverse for this, rather than the baseR function <span style="color:red">as.factor</span>.

## **Elaboration for the Singer data set**

### If necessary, transform some of the variables in the <span style="color:red">singer_locations</span> dataframe into factors: pay attention at what levels you introduce and their order.

### **Drop 0.** Filter the <span style="color:red">singer_locations</span> data to remove observations associated with the uncorrectly inputed <span style="color:red">year</span> 0. Additionally, remove unused factor levels. Provide concrete information on the data before and after removing these rows and levels; address the number of rows and the levels of the affected factors.

### **Reorder the levels of <span style="color:red">year</span>, <span style="color:red">artist_name</span> or <span style="color:red">title</span>**. Use the forcats package to change the order of the factor levels, based on a principled summary of one of the quantitative variables. Consider experimenting with a summary statistic beyond the most basic choice of the median.



# Exercise 3: File input/output (I/O)

### Task: Experiment with at least one of:
* ###  write_csv()/read_csv() (and/or TSV friends),
* ### saveRDS()/readRDS(),
* ### dput()/dget().

### You are expected to create something new, probably by filtering or grouped-summarization of your dataset (for e.g., Singer, Gapminder, or another dataset), export it to disk and then reload it back in using one of the packages above. You should use here::here() for reading in and writing out. With the imported data, play around with factor levels and use factors to order your data with one of your factors (i.e. non-alphabetically). For the I/O method(s) you chose, comment on whether or not your newly created file survived the round trip of writing to file then reading back in.

# Exercise 4: Visualization design
### Go back through your previous assignments and class participation activities and find figures you created prior to the last week of the course. Recreate at least one figure in light of something you learned in the recent class meetings about visualization design and color. Task: Create a side-by-side plot and juxtapose your first attempt (show the original figure as-is) with a revised attempt after some time spent working on it and implementing principles of effective plotting principles. Comment and reflect on the differences.

# Exercise 5: Writing figures to file
### Task: Use <span style="color:red">ggsave()</span> to explicitly save a plot to file. Include the exported plot as part of your repository and assignment.

### Then, use <span style="color:red">![Alt text] (/path/to/img.png) </span> to load and embed that file into your report. You can play around with various options, such as:

* ### Arguments of <span style="color:red">ggsave()</span>, such as width, height, resolution or text scaling.
* ### Various graphics devices, e.g. a vector vs. raster format.
* ### Explicit provision of the plot object <span style="color:red">p</span> via <span style="color:red">ggsave(..., plot = p)</span>. Show a situation in which this actually matters.
